---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: front-end
  namespace: sockshop-debug
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: front-end
    spec:
      containers:
      - name: front-end
        image: 123.207.154.16/weaveworksdemos-test/front-end:0.3.12
        resources:
          requests:
            cpu: 100m
            memory: 500Mi
        ports:
        - containerPort: 8079
        securityContext:
          runAsNonRoot: true
          runAsUser: 10001
          capabilities:
            drop:
              - all
          readOnlyRootFilesystem: true
      nodeSelector:
        kubernetes.io/hostname: 172.16.0.144