---
apiVersion: v1
kind: Service
metadata:
  name: front-end
  labels:
    name: front-end
  namespace: sockshop-debug
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8079
    nodePort: 35001
  selector:
    name: front-end
  nodeSelector:
    kubernetes.io/hostname: 172.16.0.144